name: Run Python Script Every Minute (Test)

on:
  schedule:
    - cron: '* * * * *' # This runs the script every minute
  workflow_dispatch: # This allows you to manually trigger the workflow

jobs:
  run-script-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script and log output
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: |
          {
            echo "[$(date)] Starting script..."
            python test_cron_job.py
            echo "[$(date)] Script completed successfully."
          } >> test_cron_log.txt 2>&1 || {
            echo "[$(date)] Script failed."
          } >> test_cron_log.txt 2>&1
