name: Run Python Script Every 3 Hours

on:
  schedule:
    - cron: '0 */3 * * *'  # Run the script every 3 hours
  workflow_dispatch:  # Allow manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure log file exists and set permissions
        run: |
          touch test_cron_log.txt
          chmod 666 test_cron_log.txt

      - name: Run script and log output
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: |
          {
            echo "[$(date)] Starting script..."
            python test_cron_job.py
            echo "[$(date)] Script completed successfully."
          } >> test_cron_log.txt 2>&1 || {
            echo "[$(date)] Script failed."
          } >> test_cron_log.txt 2>&1

      - name: Upload log file
        uses: actions/upload-artifact@v2
        with:
          name: cron-log
          path: test_cron_log.txt
